# Generated by Django 3.0.5 on 2022-10-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221028_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('pemail', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('department', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.CharField(max_length=13),
        ),
    ]
