# Generated by Django 3.0.5 on 2022-10-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221030_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='number',
            new_name='pnumber',
        ),
    ]
