# Generated by Django 4.1 on 2022-11-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221030_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
