# Generated by Django 4.1 on 2022-11-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_date_patient_pdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pdate',
            new_name='patientdate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pemail',
            new_name='patientemail',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pmessage',
            new_name='patientmessage',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pnumber',
            new_name='patientnumber',
        ),
    ]
